src/pages/Config.tsx, src/pages/Connections.tsx, src/pages/Rules.tsx, src/pages/Setup.tsx, src/types.d.ts
add rules pages
fix secret add
init sorting by id
config form
=> feat: rules page

src/components/Header.tsx
=> fix: theme icon height

src/pages/Proxies.tsx
=> feat: proxy point && delay

src/pages/Overview.tsx, src/pages/Proxies.tsx, src/signals/proxies.ts
make proxies selectable
fix apex charts with secret
=> feat: proxy selectable

src/pages/Setup.tsx
Bonus: this commit also prevents unusable endpoint from being selected
=> feat: prevent duplicate endpoints from being stored

src/components/Header.tsx
=> style(header): adjust rounded

src/pages/Overview.tsx
=> style(overview): adjust TrafficWidget grid cols

src/signals/request.ts
=> 支持有路径的后端地址

src/signals/request.ts
=> fix `//` in websocket path

src/components/Header.tsx
=> style(header): Add icons to the sidebar buttons

src/pages/Logs.tsx, src/signals/logs.ts, src/types/index.d.ts
A basic pause function in logs to solve issue #823
=> feat: logs pause

src/components/Header.tsx, src/components/IPv6Support.tsx, src/components/Latency.tsx, src/components/ProxyPreviewBar.tsx, src/components/ProxyPreviewDots.tsx, src/constants/index.ts, src/helpers/proxies.ts, src/pages/Connections.tsx, src/pages/Logs.tsx, src/pages/Proxies.tsx, src/pages/Rules.tsx, src/signals/logs.ts, src/signals/proxies.ts
It seems the mihomo will return 0 rather than -1 of latency when latency test is failed, and sing-box will return nothing. try fix #867 since i don't have a mihomo config, please try to see if it works @kunish
=> fix: enum of not connect for mihomo

src/components/Collapse.tsx, src/helpers/proxies.ts, src/signals/proxies.ts
=> fix: unexpected filtered proxy group

src/signals/proxies.ts
Missing loadbalance in isProxyGroup for proxy node filter
=> fix: filter for loadbalance

package.json, src/components/ConnectionsSettingsModal.tsx
Use button instead of dnd for mobile, It is a little bit ugly but it works LOL
Fixed #320
=> feat: custom table columns order for mobile

src/signals/proxies.ts
Attempting to fix an error that seemingly shouldn't have occurred
Trying to fix #889
=> fix: nil for nextnode

src/components/ProxyPreviewBar.tsx, src/helpers/global.ts, src/pages/Config.tsx, src/signals/version.ts
Fix flickering of config page 
Fix the height for bar preview to align with dots preview
=> fix: flickering issue of the config page under sing-box

src/pages/Connections.tsx, src/pages/Proxies.tsx, src/pages/Rules.tsx
=> style: Fix the abnormal left padding of the tabs.

src/pages/Proxies.tsx, src/signals/connections.ts
=> feat: preview dlspeed in proxies page

src/pages/Proxies.tsx
improve readability for preview
=> fix: improve readability for dlspeed preview

src/constants/index.ts, src/pages/Config.tsx, src/types/index.d.ts
Support dynamic acquisition of clash_mode
There is already an agent [core](https://github.com/PuerNya/sing-box/tree/building) that supports this API
=> feat: Support dynamic acquisition of clash_mode

src/pages/Setup.tsx
Update placeholder and options for setup form
=> feat: optimize setup form

src/signals/logs.ts, src/signals/request.ts
Reconnect websocket when logs level has changed
=> feat: reconnect ws when logs level changed

src/components/ProxiesSettingsModal.tsx, src/i18n/en.ts, src/i18n/zh.ts, src/pages/Proxies.tsx, src/signals/config.ts
Use config for icon style to adapt with different icon
=> feat: config for icon height and margin-right

src/components/ProxiesRenderWrapper.tsx, src/pages/Proxies.tsx
Implement two columns mode without using a grid layout to eliminate gaps.
=> feat: dual column for proxies render

src/pages/Config.tsx, src/types/index.d.ts
https://github.com/SagerNet/sing-box/pull/2300/files
=> feat: modes list for sing-box official

src/components/ProxyNodeCard.tsx, src/signals/proxies.ts
=> fix: latency not correct when proxy group has custom test url

src/components/ProxyPreviewBar.tsx, src/components/ProxyPreviewDots.tsx, src/components/SubscriptionInfo.tsx, src/pages/Proxies.tsx
=> style: adjust the card styles of the proxy group and proxy providers.

src/pages/Config.tsx
=> chore: display the current endpoint on the configuration page.

src/components/ProxyPreviewBar.tsx, src/components/ProxyPreviewDots.tsx, src/helpers/proxies.ts
Fixed latency color to prevent unclear visibility in certain themes.
=> fix: fixed latency color

package.json, pnpm-lock.yaml, src/pages/Connections.tsx
Replace For with Key for table tr
=> fix: table tr keyed

package.json, pnpm-lock.yaml, src/pages/Connections.tsx
This reverts commit cd273598a9fc7b25f023621e2cfc99b41353262d. Sorry for the chaos i made
=> Revert "fix: table tr keyed (#1261)"

src/pages/Rules.tsx
=> fix(rules): fix rules search (#1267)

src/components/Collapse.tsx
Refactor calculate of grid cols with min-width css
=> refactor: calc of grids cols

src/App.tsx
=> fix: bg color
